### PR TITLE
Add support for screenshots

### PR DESCRIPTION
**Pull request by dressupgeekout**
You can hit Control-P to dump the framebuffer's contents to a BMP file.

I picked Ctrl-P almost completely randomly, there's probably a more sensible choice.

I also wonder if the directory into which the screenshots are written should be configurable by the user.

### CODE REVIEW

**Comment by irmen** [comment]
I don't know SDL but is there perhaps a routine to dump it as PNG instead?  Much smaller and more cross platform

**Comment by dressupgeekout** [comment]
That's fair. I'd prefer to write PNG as well -- but SDL2's base library only provides this BMP writer.

If we want to support PNG then we'd have to bring in SDL2_img, or use libpng directly, I suppose (either way we'd be introducing a whole new dependency). Otherwise we could most likely get away with 'stb_img' https://github.com/nothings/stb/blob/master/stb_image_write.h -- That way, we can still claim that SDL2 is the only dependency like it says in the README.

**Comment by dressupgeekout** [comment]
OK, how about this version? I'm using the STB PNG writer

**Comment by irmen** [comment]
I like that you tried to keep the dependencies minimal but it's too bad there's no PNG writer in SDL itself already.
It's up to the maintainers to decide if the stb_png header addition is acceptable as a (small) new dependency. Otherwise I'm not opposed to the BMP writer, I just prefer PNGs

**Review by mooinglemur — APPROVED** [review]

**Review by mooinglemur — CHANGES_REQUESTED** [review]
Actually, since this fails to build the wasm version, we can either fix that or `#ifndef` out the feature for the wasm build.  I actually don't care either way. :)

**Comment by dressupgeekout** [comment]
I suppose it doesn't make much sense to save screenshots to disk when you're interacting with the emulator in a web browser?

(I actually have no idea how Emscripten works)

**Comment by mooinglemur** [comment]
> I suppose it doesn't make much sense to save screenshots to disk when you're interacting with the emulator in a web browser?
> 
> (I actually have no idea how Emscripten works)

The screenshots would actually have landed on the wasm build's version of the host filesystem (a construct within the browser's memory).  Currently there's no way to access those files from the host side, but rather from within the emulator itself.

**Review by mooinglemur — APPROVED** [review]
Thanks!

**Pull request merged**
